import LazyLoad from "vanilla-lazyload";
import Swiper from "swiper";
import { Navigation, Pagination } from "swiper/modules";
import { isBrowserSupportWebp } from "./modules/support-webp.js";
// import "@fancyapps/ui/dist/fancybox/fancybox.css";

import { toggleModalWindow } from "./modules/toggle-modal-window.js";
import { animCircleText } from "./modules/animate-circle.js";
import { validInputs } from "./modules/valid-inputs.js";
import { formHandle } from "./modules/form-handle.js";
import { validateForm } from "./modules/validate.js";
import { handleMobileMenu } from "./modules/mobile-menu.js";
import { accordeonFunc } from "./modules/accordeon.js";
import { blogHandledFunc } from "./modules/blog-handled.js";
import { swiper } from "./modules/swiper.js";
import { map } from "./modules/map.js";
import { loader } from "./modules/loader.js";
import { selector } from "./modules/selector.js";
import { catalog } from "./modules/catalog.js";
import { modal } from "./modules/modal.js";
import { search } from "./modules/search.js";
import { header } from "./modules/header.js";
import { sort } from "./modules/sort.js";
import { fancy } from "./modules/fancy.js";
import { calcTrade } from "./modules/calc-trade.js";
import { doubleRange } from "./modules/double-range.js";
import { testDrive } from "./modules/test-drive.js";
import { datePicker } from "./modules/date-picker.js";
import { text } from "./modules/text.js";
import { video } from "./modules/video.js";

datePicker();
fancy();
testDrive();
text();
video();
loader();
doubleRange();
header();
sort();
modal();
// search();
catalog();
selector();
isBrowserSupportWebp();
swiper();
toggleModalWindow();
map();
animCircleText();
validInputs();
formHandle();
validateForm();
handleMobileMenu();
accordeonFunc();
blogHandledFunc();
calcTrade();
let myLazyLoad = new LazyLoad();
myLazyLoad.update();
